In [25]:
!pip3 install webdriver-manager --upgrade

Requirement already satisfied: webdriver-manager in c:\users\huhsu\anaconda3\lib\site-packages (4.0.1)
Requirement already satisfied: requests in c:\users\huhsu\anaconda3\lib\site-packages (from webdriver-manager) (2.28.1)
Requirement already satisfied: python-dotenv in c:\users\huhsu\anaconda3\lib\site-packages (from webdriver-manager) (1.0.0)
Requirement already satisfied: packaging in c:\users\huhsu\anaconda3\lib\site-packages (from webdriver-manager) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\huhsu\anaconda3\lib\site-packages (from packaging->webdriver-manager) (3.0.9)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\huhsu\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\huhsu\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\huhsu\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\huhsu\anaconda3\lib\site-packages (from requests->webdriver-manager) (2022.9.14)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [27]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

C:\Users\huhsu\AppData\Local\Temp\ipykernel_14128\1781563638.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

Hitters Data

In [4]:
col_hit = ['순', '이름', '팀', 'WAR*', 'G', '타석', '타수', '득점', '안타', '2타', '3타', '홈런', '루타', '타점',
       '도루', '도실', '볼넷', '사구', '고4', '삼진', '병살', '희타', '희비', '타율', '출루', '장타', 'OPS', 'wOBA', 'wRC+',""'WAR*','WPA']

df_hitter = pd.DataFrame(columns=col_hit)

In [5]:
for i in range(85):
    url='http://www.statiz.co.kr/stat.php?mid=stat&re=0&ys=2016&ye=2022&se=0&te=&tm=&ty=0&qu=auto&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR_ALL_ADJ&o2=TPA&de=1&lr=0&tr=&cv=&ml=1&sn=30&pa='+str(i*30)+'&si=&cn='
    driver.get(url)
    
    xpath='/html/body/div/div[1]/div/section[2]/div/div[2]/div[5]/div/div/div[2]'
    data=driver.find_element(By.XPATH,xpath).text
    
    data.split(sep='\n')
    lines = data.split('\n')

    data_list = [line.split() for line in lines]
    
    remove=data_list[:30]

    my_list = [x for x in data_list if x not in remove]
    
    for row in my_list:
        if len(row) != len(col_hit):
            pass
        else:
            df_hitter.loc[len(df_hitter)] = row

http://www.statiz.co.kr/stat.php?mid=stat&re=0&ys=2016&ye=2022&se=0&te=&tm=&ty=0&qu=auto&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR_ALL_ADJ&o2=TPA&de=1&lr=0&tr=&cv=&ml=1&sn=30&pa=0&si=&cn=

http://www.statiz.co.kr/stat.php?mid=stat&re=0&ys=2016&ye=2022&se=0&te=&tm=&ty=0&qu=auto&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR_ALL_ADJ&o2=TPA&de=1&lr=0&tr=&cv=&ml=1&sn=30&pa=30&si=&cn=


http://www.statiz.co.kr/stat.php?mid=stat&re=0&ys=2016&ye=2022&se=0&te=&tm=&ty=0&qu=auto&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR_ALL_ADJ&o2=TPA&de=1&lr=0&tr=&cv=&ml=1&sn=30&pa=60&si=&cn=

In [7]:
df_hitter.tail()

,순,이름,팀,WAR*,G,타석,타수,득점,안타,2타,...,희타,희비,타율,출루,장타,OPS,wOBA,wRC+,WAR*,WPA
1943,2545,이해창,16kC,-1.21,88,254,231,16,47,10,...,8,3,.203,.240,.325,.565,.246,25.1,-1.21,-2.38
1944,2546,조인성,16한C,-1.36,76,146,137,10,23,2,...,6,0,.168,.186,.248,.434,.188,-12.4,-1.36,-1.88
1945,2547,나종덕,19롯C,-1.41,104,209,185,12,23,4,...,7,2,.124,.188,.195,.383,.180,-4.2,-1.41,-2.74
1946,2548,김헌곤,22삼CF,-1.58,80,239,224,18,43,8,...,2,3,.192,.224,.241,.465,.217,24.6,-1.58,-2.24
1947,2549,나종덕,18롯C,-1.71,106,203,177,15,22,3,...,9,0,.124,.201,.175,.376,.175,-15.1,-1.71,-1.85

In [8]:
df_hitter.to_csv('../raw_data/2016~2022 hitters.csv', index=False)

--TODO <br/>
/html/body/div/div[1]/div/section[2]/div/div[2]/div[5]/div/div/div[4]/table/tbody/tr/td[2]/a[2]<br/>
이거 누르면 다음 페이지로 넘어감(com)<br/>
for 돌려서 data append 시키기(com)

Pitchers Data

In [64]:
col_pit=['순', '이름', '팀','WAR','출장','완투','완봉','선발','승','패','세','홀드','이닝','실점','자책','타자','안타','2타','3타','홈런','볼넷','고4','사구','삼진','보크','폭투','ERA','FIP','WHIP','ERA+','FIP+','WAR(need to drop)','WPA']
df_pitcher=pd.DataFrame(columns=col_pit)

In [65]:
for i in range(63):
    url='http://www.statiz.co.kr/stat.php?mid=stat&re=1&ys=2016&ye=2022&se=0&te=&tm=&ty=0&qu=auto&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR&o2=OutCount&de=1&lr=0&tr=&cv=&ml=1&sn=30&pa='+str(i*30)+'&si=&cn='
    driver.get(url)
    xpath='/html/body/div/div[1]/div/section[2]/div/div[2]/div[5]/div/div/div[2]'
    data=driver.find_element(By.XPATH,xpath).text
    
    data.split(sep='\n')
    lines = data.split('\n')
    data_list = [line.split() for line in lines]
    remove=data_list[:32]
    my_list = [x for x in data_list if x not in remove]
    for row in my_list:
        if len(row) != len(col_pit):
            pass
        else:
            df_pitcher.loc[len(df_pitcher)] = row

In [66]:
df_pitcher.tail()

,순,이름,팀,WAR,출장,완투,완봉,선발,승,패,...,삼진,보크,폭투,ERA,FIP,WHIP,ERA+,FIP+,WAR(need to drop),WPA
1791,1874,윤대경,22한,-1.37,25,0,0,14,4,9,...,51,0,5,7.41,3.98,1.63,54.7,102.6,-1.37,-2.23
1792,1875,장시환,21한,-1.38,19,1,0,16,0,11,...,47,0,7,7.04,4.99,1.96,62.2,89.5,-1.38,-2.32
1793,1876,유희관,21두,-1.48,15,0,0,15,4,7,...,23,0,0,7.71,5.95,2.08,55.9,71.8,-1.48,-1.98
1794,1877,장현식,20NK,-1.67,37,0,0,3,4,4,...,26,0,11,10.76,6.65,2.10,44.8,72.2,-1.67,-2.09
1795,1878,장원준,18두,-2.19,24,0,0,16,3,7,...,46,0,3,9.92,6.57,1.87,51.0,76.4,-2.19,-3.12

In [67]:
df_pitcher.to_csv('../raw_data/2016~2022 pitchers.csv', index = False)